credentials:
  usernames:
    testuser:
      email: testuser@example.com
      name: Test User
      password: $2b$12$RisrHMJQ9TuHBVvpDQYWmemK.FS7j.eyyGir39w.GRmKIqDFC7n2abc123  # Use a hashed password in production

cookie:
  name: carbon_tracker_cookie
  key: random_secret_key
  expiry_days: 30
